/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poll.contract;

import score.Address;
import score.Context;
import score.VarDB;
import score.annotation.External;
import score.ArrayDB;
import score.DictDB;

import java.math.BigInteger;

public class Poll {
    private static final String VOTER_ADDRESS = "voterAddress";
    final static DictDB<String, String> voters = Context.newDictDB(VOTER_ADDRESS, String.class);
    private final VarDB<BigInteger> countOfNo = Context.newVarDB("countOfNo", BigInteger.class);
    private final VarDB<BigInteger> countOfYes = Context.newVarDB("countOfYes", BigInteger.class);

    @External
    public String addVoteYes() {
        Address _caller = Context.getCaller();
        String _addressVote = voters.getOrDefault(_caller.toString(), "null");
        String result = "Account already voted";
        if (_addressVote == "null") {
            result = "Voted Yes";
            voters.set(_caller.toString(), "yes");
            countOfYes.set(countOfYes.getOrDefault(BigInteger.ZERO).add(BigInteger.ONE));
        }
        return result;
    }

    @External
    public String addVoteNo() {
        Address _caller = Context.getCaller();
        String _addressVote = voters.getOrDefault(_caller.toString(), "null");
        String result = "Account already voted";
        if (_addressVote == "null") {
            result = "Voted No";
            voters.set(_caller.toString(), "no");
            countOfNo.set(countOfNo.getOrDefault(BigInteger.ZERO).add(BigInteger.ONE));
        }
        return result;
    }

    @External(readonly=true)
    public String checkVote(String _address) {
        return voters.get(_address);
    }

    @External(readonly=true)
    public BigInteger getVotesResult() {
        return countOfNo.getOrDefault(BigInteger.ZERO).add(countOfYes.getOrDefault(BigInteger.ZERO));
    }
}
